
=== Get the sample application and build it

```
git clone https://github.com/sqshq/PiggyMetrics
mvn clean package -DskipTests -f PiggyMetrics/pom.xml
```

=== Install jQAssistant

```
curl -O https://jqassistant.org/wp-content/uploads/2018/12/jqassistant-commandline-neo4jv3-1.6.0-distribution.zip
unzip jqassistant-commandline-neo4jv3-1.6.0-distribution.zip
mv jqassistant-commandline-neo4jv3-1.6.0 jqassistant
```

=== Scan the example application

```
./jqassistant/bin/jqassistant.sh scan -p config/scan.properties -f PiggyMetrics/account-service/target/account-service.jar,PiggyMetrics/auth-service/target/auth-service.jar,PiggyMetrics/notification-service/target/notification-service.jar,PiggyMetrics/statistics-service/target/statistics-service.jar,PiggyMetrics/config/target/config.jar
```

By default, jQAssistant will create an embedded database, which can be started with
`./jqassistant/bin/jqassistant.sh server`

If you want to import to you locally running database, add these arguments to the command line when scanning
`-storeUri bolt://localhost -storeUsername neo4j -storePassword password`

We'll use the latter in our examples with a local neo4j DB accessible on `http://localhost:7474`,
with the https://neo4j.com/developer/neo4j-apoc/[APOC] library installed.

=== Running some rules

jQAssistant comes out of the box with some plugins that help us, such as the
Spring plugin, so we can use it to enrich our existing database
to create some additional concepts like REST controllers, repositories, etc

```
./jqassistant/bin/jqassistant.sh analyze -concepts classpath:Resolve -storeUri bolt://localhost -storeUsername neo4j -storePassword password
./jqassistant/bin/jqassistant.sh analyze -groups spring-boot:Default -storeUri bolt://localhost -storeUsername neo4j -storePassword password
```

We can explore the graph and check spring repositories are present with

[source,cypher,role=concept]
----
MATCH (r:Spring:Repository)
WHERE r.fqn STARTS WITH 'com'
RETURN *
----

*From now on, you can run the queries below manually, or use the script `runAnalysis.sh` to run them automatically.*



// Below is an ugly copy of microservices-rules.adoc, as github does not support asciidoc includes
// see https://github.com/github/markup/issues/1095

